name: Manifesto
markdown: kramdown
highlighter: pygments
exclude: [
    "LICENSE.txt",
    "README.md",
    "*.json",
    "Gemfile*",
    "*.txt",
    ".idea/*",
    ".jekyll-cache/*",
    "build.sh",
    "deploy.sh"
]

baseurl: "/"
permalink: /:title/


# Paginate
paginate: 5
paginate_path: "/pagination/page:num/"


# Manifest
manifestVersion: 1.1
mPath: manifest/lidimist_manifest

# Plugins
plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-paginate


# jekyll-multiple-languages-plugin settings:
languages: ["pt-br", "en"]
default_locale_in_subfolder: false

exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico"]
