#
# Configuration flags
#
name: Lidimismo
author: Rodrigo Favarete
avatar: /images/lidimism.png
description: Movimento Lidimista

# Includes an icon in the footer for each username
footer-links:
  dribbble:
  email: rodrigo@favarete.art
  facebook:
  flickr:
  github: favarete/manifesto
  instagram: rodrigofavarete
  linkedin: 
  pinterest:
  rss: rss
  twitter:
  stackoverflow: 
  youtube: # channel/<long_string> or user/<user-name>
  googleplus: # anything that comes after plus.google.com/
  playconsole:


# Disqus shortname (from the Settings page oof the Disqus account) to enable commenting on posts
disqus: 

# Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-43339302-11

# For newer "GA4" analytics, use the following instead of the "UA" entry above
#google_analytics_ga4: G-GABC1DEFG

# Website URL
# Used for Sitemap.xml and your RSS feed
url: http://favarete.github.io/manifesto
enforce_ssl: https://favarete.github.io/manifesto

# If hosting the site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT the User repository (http://yourusername.github.io)
# then the baseurl will be like this: "/repository-name"
baseurl: "/"
articlesurl: "/publicacoes"
textReview: "Rev1"

#
# !! System flags
#

permalink: /:title/

# The release of Jekyll Now
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory
sass:
  style: :expanded # Might prefer to minify using :compressed

# Plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - jekyll-paginate

include: ['_pages']

paginate: 6
paginate_path: "/publicacoes/pagina:num/"


# Exclude these files from the production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

